// Auto Generated By JsonToScriptableObjectWidnow

using UnityEngine; 
using System.Collections; 
using System; 
using System.Runtime.InteropServices; 
using DevelopeCommon; 

[System.Serializable]
public class Scriptable_Lotto_Element
{
    public int inning = 0;
    public int number_1 = 0;
    public int number_2 = 0;
    public int number_3 = 0;
    public int number_4 = 0;
    public int number_5 = 0;
    public int number_6 = 0;
    public int bonus = 0;
}

public class Scriptable_Lotto : ScriptableObject, IScriptableObject
{
    public Scriptable_Lotto_Element[] _arr_data = null;

    public void SetData(string json_data_txt)
    {
        JSONObject jo = new JSONObject(json_data_txt);

        _arr_data = new Scriptable_Lotto_Element[jo.list.Count];

        for (int i = 0; i < jo.list.Count; ++i)
        {
            _arr_data[i] = new Scriptable_Lotto_Element();

            JSONObject jo_element = (JSONObject)jo.list[i];

            int index = 0;

            if (jo_element.keys[index] == "inning") _arr_data[i].inning = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "number_1") _arr_data[i].number_1 = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "number_2") _arr_data[i].number_2 = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "number_3") _arr_data[i].number_3 = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "number_4") _arr_data[i].number_4 = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "number_5") _arr_data[i].number_5 = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "number_6") _arr_data[i].number_6 = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;

            if (jo_element.keys[index] == "bonus") _arr_data[i].bonus = jo_element.list[index].str.Length > 0 ? int.Parse(jo_element.list[index].str) : 0;
            else Debug.LogError("weird");
            index++;
        }
    }
    public Scriptable_Lotto_Element GetElement(string inning)
    {
        for (int i = 0; i < _arr_data.Length; ++i)
        {
            if (inning.Equals(_arr_data[i].inning))
            {
                return _arr_data[i];
            }
        }

        Debug.Log(string.Format("GetElement() : inning Not found", inning));
        return null;
    }

    public Scriptable_Lotto_Element [] GetArray()
    {
        return _arr_data;
    }
}
